name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.3
  - python=3.7       
  - numpy=1.18.5
  - pip=20.3.3
  - scikit-learn=0.24.1
  - pip:
      - wandb==0.10.21
      - protobuf==3.20.3