name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.24.0
  - pip=20.3.3
  - mlflow=1.14.1
  - python=3.7       
  - numpy=1.18.5
  - hydra-core=1.0.6
  - pip:
      - wandb==0.10.21
      - hydra-joblib-launcher==1.1.2
      - protobuf==3.20.3
