name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - notebook
  - seaborn=0.11.1
  - pandas=1.2.3
  - numpy=1.18.5
  - pip=20.3.3
  - pandas-profiling=2.11.0
  - Jinja2=3.0.3
  - pyarrow=2.0
  - pip:
      - wandb==0.10.21
      - protobuf==3.20.3