name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - requests=2.24.0
  - numpy=1.18.5
  - pip=20.3.3
  - seaborn=0.11.1
  - pandas=1.2.3
  - Jinja2=3.0.3      
  - scikit-learn=0.24.1
  - matplotlib==3.2.2
  - pillow=8.1.2
  - pip:
      - wandb==0.10.21
      - protobuf==3.20.3